const TEMPLATES = [
  {id:'IMG_SM', label:'IMG (Smartphone)', pattern:'IMG XXXX', vars:[{name:'XXXX',type:'digits',len:4,range:[0,9999]}], category:'new', sub:'phone'},
  {id:'MVI_CAM', label:'MVI (Camera)', pattern:'MVI XXXX', vars:[{name:'XXXX',type:'digits',len:4}] ,category:'new', sub:'camera'},
  {id:'YMD_MISC', label:'YMD (YYYYMMDD) (Misc)', pattern:'YMD', vars:[{name:'date',type:'date',format:'YYYYMMDD',range:[new Date(2018,0,1), new Date(2026,11,31)]}], category:'new', sub:'misc'},
  {id:'WIN_YMD', label:'WIN YMD (WIN YYYYMMDD) (Webcam)', pattern:'WIN YMD', vars:[{name:'date',type:'date',format:'YYYYMMDD'}], category:'new', sub:'webcam'},
  {id:'CAPTURE_YMD', label:'Capture YMD (Webcam)', pattern:'Capture YMD', vars:[{name:'date',type:'date',format:'YYYYMMDD'}], category:'new', sub:'webcam'},
  {id:'VID_YMD', label:'VID YMD', pattern:'VID YMD', vars:[{name:'date',type:'date',format:'YYYYMMDD'}], category:'new', sub:'phone'},
  {id:'MY_MOVIE_X', label:'"My Movie X" / "My Movie 1" (Misc)', pattern:'My Movie X', vars:[{name:'X',type:'digits',len:1,range:[1,9]}], category:'new', sub:'misc'},
  {id:'MY_EDITED', label:'"My Edited Video" (Video Editor)', pattern:'My Edited Video', vars:[], category:'new', sub:'video_editor'},
  {id:'STORAGE', label:'/Storage/Emulated/ (Video editor)', pattern:'/Storage/Emulated/', vars:[], category:'new', sub:'video_editor'},
  {id:'PXL', label:'PXL (Smartphone)', pattern:'PXL YYYYMMDD', vars:[{name:'date',type:'date',format:'YYYYMMDD'}], category:'new', sub:'phone'},
  {id:'INSHOT', label:'InShot YMD (App)', pattern:'InShot YMD', vars:[{name:'date',type:'date',format:'YYYYMMDD'}], category:'new', sub:'app'},
  {id:'WHATSAPP', label:'WhatsApp Video YYYY (App)', pattern:'WhatsApp Video YYYY', vars:[{name:'year',type:'year',range:[2015,2026]}], category:'new', sub:'app'},
  {id:'FULLSIZERENDER', label:'FullSizeRender (Smartphone)', pattern:'FullSizeRender', vars:[], category:'new', sub:'phone'},
  {id:'RPREPLAY', label:'RPReplay (Screen Recorder)', pattern:'RPReplay YYYY', vars:[{name:'year',type:'year'}], category:'new', sub:'screen_recorder'},
  {id:'VTS01', label:'VTS 01 (VHS/legacy)', pattern:'VTS 01', vars:[], category:'new', sub:'legacy'},
  {id:'DVR', label:'DVR (Game Capture)', pattern:'DVR', vars:[], category:'new', sub:'game_capture'},
  {id:'VLC', label:'VLC Record', pattern:'VLC Record', vars:[], category:'new', sub:'misc'},
  {id:'ROBLOXAPP', label:'Robloxapp (Game Capture)', pattern:'Robloxapp', vars:[], category:'new', sub:'game_capture'},
  {id:'FORMAT_MP4', label:'".MP4" ".3gp" ".MOV" ".AVI" (format hints)', pattern:'.MP4', vars:[], category:'new', sub:'format'},
  {id:'FLAC', label:'".FLAC" (Copyright music)', pattern:'.FLAC', vars:[], category:'new', sub:'format'},
  {id:'WAV', label:'".WAV" (User-created music)', pattern:'.WAV', vars:[], category:'new', sub:'format'},
  {id:'RECORDING_GVO', label:'Recording gvo (Zoom)', pattern:'Recording gvo', vars:[], category:'new', sub:'zoom'},
  {id:'LV0', label:'Lv 0', pattern:'Lv 0', vars:[], category:'new', sub:'misc'},
  {id:'BMDJ', label:'bmdjAAAF (Misc)', pattern:'bmdjAAAF', vars:[], category:'new', sub:'misc'},
  {id:'YOUCUT', label:'YouCut YMD (Misc)', pattern:'YouCut YMD', vars:[{name:'date',type:'date',format:'YYYYMMDD'}], category:'new', sub:'misc'},
  {id:'VIDEO_YMD', label:'"Video YMD" (Camera)', pattern:'"Video YMD"', vars:[{name:'date',type:'date',format:'YYYYMMDD'}], category:'new', sub:'camera'},
  {id:'COPYOFCOPY', label:'"Copy of Copy of" (Misc)', pattern:'"Copy of Copy of"', vars:[], category:'new', sub:'misc'},
  {id:'UNTITLED', label:'"Untitled video" (Misc)', pattern:'"Untitled video"', vars:[], category:'new', sub:'misc'},
  {id:'YTPMV', label:'"YTPMV" (Video Editor)', pattern:'"YTPMV"', vars:[], category:'new', sub:'video_editor'},
  {id:'KLASKY', label:'"Klasky Csupo" (Video Editor)', pattern:'"Klasky Csupo"', vars:[], category:'new', sub:'video_editor'},
  {id:'OCULUS_VR', label:'"Com Oculus Vrshell" (VR)', pattern:'"Com Oculus Vrshell"', vars:[], category:'new', sub:'vr'},
  {id:'OCULUS_META', label:'"Com Oculus Metacam" (VR)', pattern:'"Com Oculus Metacam"', vars:[], category:'new', sub:'vr'},
  {id:'DESKTOP_DATE', label:'Desktop YYYY MM DD (Game Capture)', pattern:'Desktop YYYY MM DD', vars:[{name:'date',type:'date',format:'YYYY MM DD'}], category:'new', sub:'game_capture'},
  {id:'IMG_OLD', label:'IMG XXXX (old camera)', pattern:'IMG XXXX', vars:[{name:'XXXX',type:'digits',len:4}], category:'old', sub:'camera'},
  {id:'MOV_OLD', label:'MOV XXXX (camera)', pattern:'MOV XXXX', vars:[{name:'XXXX',type:'digits',len:4}], category:'old', sub:'camera'},
  {id:'DSC', label:'DSC XXXX (camera)', pattern:'DSC XXXX', vars:[{name:'XXXX',type:'digits',len:4}], category:'old', sub:'camera'},
  {id:'DSCF', label:'DSCFXXXX (camera)', pattern:'DSCF XXXX', vars:[{name:'XXXX',type:'digits',len:4}], category:'old', sub:'camera'},
  {id:'GOPRO', label:'GOPRXXXX / GH01XXXX (GoPro)', pattern:'GOPRXXXX', vars:[{name:'XXXX',type:'digits',len:4}], category:'old', sub:'gopro'},
  {id:'DJI', label:'DJI XXXX (Drone)', pattern:'DJI XXXX', vars:[{name:'XXXX',type:'digits',len:4}], category:'old', sub:'drone'},
  {id:'HNI', label:'HNI_XXXX (Nintendo DS)', pattern:'HNI_XXXX', vars:[{name:'XXXX',type:'digits',len:4}], category:'old', sub:'handheld'},
  {id:'WAO', label:'WAOXXXX (misc)', pattern:'WAOXXXX', vars:[{name:'XXXX',type:'digits',len:4}], category:'old', sub:'misc'},
  {id:'MOLOX', label:'MOLOX (old misc)', pattern:'MOLOX', vars:[], category:'old', sub:'misc'},
  {id:'P100', label:'P100XXXX (camera)', pattern:'P100XXXX', vars:[{name:'XXXX',type:'digits',len:4}], category:'old', sub:'camera'},
  {id:'VTS_OLD', label:'VTS XXX (VHS)', pattern:'VTS XXX', vars:[{name:'XXX',type:'digits',len:3}], category:'old', sub:'legacy'},
  {id:'MY_SLIDESHOW', label:'"My Slideshow" / "My Slideshow Video" (Video Editor)', pattern:'My Slideshow Video', vars:[], category:'old', sub:'video_editor'},
  {id:'MY_STUPEFLIX', label:'"My Stupeflix Video" (Video Editor)', pattern:'My Stupeflix Video', vars:[], category:'old', sub:'video_editor'},
  {id:'YMD_OLD', label:'YMD patterns (old)', pattern:'YMD', vars:[{name:'date',type:'date',format:'YYYYMMDD',range:[new Date(2005,0,1), new Date(2018,11,31)]}], category:'old', sub:'misc'},
  {id:'VID_YMD_OLD', label:'VID YMD (old)', pattern:'VID YMD', vars:[{name:'date',type:'date',format:'YYYYMMDD',range:[new Date(2005,0,1), new Date(2018,11,31)]}], category:'old', sub:'camera'},
  {id:'INSHOT_OLD', label:'InShot YMD (>2016)', pattern:'InShot YMD', vars:[{name:'date',type:'date',format:'YYYYMMDD',range:[new Date(2016,0,1), new Date(2021,11,31)]}], category:'old', sub:'app'},
  {id:'PXL_OLD', label:'PXL YMD (>2020)', pattern:'PXL YMD', vars:[{name:'date',type:'date',format:'YYYYMMDD',range:[new Date(2020,0,1), new Date(2022,11,31)]}], category:'old', sub:'phone'},
  {id:'AUD_YMD', label:'AUD-YMD (>2017)', pattern:'AUD-YMD', vars:[{name:'date',type:'date',format:'YYYYMMDD',range:[new Date(2017,0,1), new Date(2020,11,31)]}], category:'old', sub:'audio'},
  {id:'WHATSAPP_OLD', label:'WhatsApp Video YYYY MM DD (>2015)', pattern:'WhatsApp Video YYYY MM DD', vars:[{name:'date',type:'date',format:'YYYY MM DD',range:[new Date(2015,0,1), new Date(2020,11,31)]}], category:'old', sub:'app'},
  {id:'DESKTOP_OLD', label:'Desktop YYYY MM DD (old)', pattern:'Desktop YYYY MM DD', vars:[{name:'date',type:'date',format:'YYYY MM DD',range:[new Date(2008,0,1), new Date(2016,11,31)]}], category:'old', sub:'game_capture'},
  {id:'AXON', label:'"Axon Body * Video" (Body Cam)', pattern:'"Axon Body * Video"', vars:[], category:'old', sub:'bodycam'},
  {id:'WP_YMD', label:'WP YMD (Misc) (>2011)', pattern:'WP YMD', vars:[{name:'date',type:'date',format:'YYYYMMDD',range:[new Date(2011,0,1), new Date(2015,11,31)]}], category:'old', sub:'misc'},
  {id:'KAKAOTALK', label:'KakaoTalk Video YYYY MM (Misc)', pattern:'KakaoTalk Video YYYY MM', vars:[{name:'date',type:'date',format:'YYYY MM',range:[new Date(2012,0,1), new Date(2016,11,31)]}], category:'old', sub:'app'},
  {id:'AVSEQ', label:'AVSEQXX.DAT (misc)', pattern:'AVSEQXX.DAT', vars:[{name:'XX',type:'digits',len:2}], category:'old', sub:'misc'},
  {id:'MOV_OLDNUM', label:'MOVXXXX (0000-1050) Drone/Dashcam', pattern:'MOVXXXX', vars:[{name:'XXXX',type:'digits',len:4,range:[0,1050]}], category:'old', sub:'dashcam'},
  {id:'GMTYMD', label:'GMTYMD (Zoom)', pattern:'GMTYMD', vars:[{name:'date',type:'date',format:'YYYYMMDD'}], category:'old', sub:'zoom'},
  {id:'KVID', label:'KVIDXXXX (camera)', pattern:'KVIDXXXX', vars:[{name:'XXXX',type:'digits',len:4}], category:'old', sub:'camera'},
  {id:'VIDEOLIC', label:'"My Videolicious Video" (Video Editor)', pattern:'My Videolicious Video', vars:[], category:'old', sub:'video_editor'},
  {id:'M2U', label:'M2U0XXXX (misc)', pattern:'M2U0XXXX', vars:[{name:'XXXX',type:'digits',len:4}], category:'old', sub:'misc'},
  {id:'GH01', label:'GH01XXXX (GoPro)', pattern:'GH01XXXX', vars:[{name:'XXXX',type:'digits',len:4}], category:'old', sub:'gopro'},
  {id:'MONTH_DD_YYYY', label:'"Month DD, YYYY" (Phone formatted date)', pattern:'Month DD, YYYY', vars:[{name:'date',type:'date',format:'MONTH DD, YYYY'}], category:'old', sub:'phone'},
  {id:'MAH', label:'MAH0XXXX (camera)', pattern:'MAH0XXXX', vars:[{name:'XXXX',type:'digits',len:4}], category:'old', sub:'camera'},
  {id:'CIMG', label:'CIMGXXXX (camera)', pattern:'CIMGXXXX', vars:[{name:'XXXX',type:'digits',len:4}], category:'old', sub:'camera'},
  {id:'IMGP', label:'IMGPXXXX (camera)', pattern:'IMGPXXXX', vars:[{name:'XXXX',type:'digits',len:4}], category:'old', sub:'camera'},
  {id:'VIDEO_OLDNUM', label:'VideoXXXX (camera)', pattern:'VideoXXXX', vars:[{name:'XXXX',type:'digits',len:4}], category:'old', sub:'camera'},
  {id:'MOV0', label:'MOV0XXXX (camera)', pattern:'MOV0XXXX', vars:[{name:'XXXX',type:'digits',len:4}], category:'old', sub:'camera'},
  {id:'VID_240P_400K', label:'240p 400k (nsfw)', pattern:'240p 400k', vars:[], category:'old', sub:'format'},
  {id:'VID_480P_600K', label:'480p 600k (nsfw)', pattern:'480p 600k', vars:[], category:'old', sub:'format'},
  {id:'VID_480P_2000K', label:'480p 2000k (nsfw)', pattern:'480p 2000k', vars:[], category:'old', sub:'format'},
  {id:'VID_720P_1500K', label:'720p 1500k (nsfw)', pattern:'720p 1500k', vars:[], category:'old', sub:'format'},
  {id:'VID_720P_4000K', label:'720p 4000k (nsfw)', pattern:'720p 4000k', vars:[], category:'old', sub:'format'},
  {id:'CLIPS4SALE', label:'Clips4Sale (nsfw)', pattern:'Clips4Sale', vars:[], category:'old', sub:'misc'}
];

const SUBCAT_DETAILS = {
  phone: { name: "Phones", description: "Finds videos with default filenames from smartphones (e.g., IMG_XXXX, PXL_YYYYMMDD)." },
  camera: { name: "Cameras", description: "Searches for common digital camera file naming conventions like DSC_XXXX or MVI_XXXX." },
  misc: { name: "Miscellaneous", description: "A variety of general search terms, including generic date formats and common placeholder titles." },
  webcam: { name: "Webcams", description: 'Targets videos uploaded directly from webcam software, often containing prefixes like "WIN" or "Capture".' },
  video_editor: { name: "Video Editors", description: 'Looks for default export titles from editing software, such as "My Edited Video" or "My Slideshow".' },
  app: { name: "Apps", description: "Templates from mobile apps like WhatsApp, InShot, or KakaoTalk." },
  screen_recorder: { name: "Screen Recorders", description: "Finds screen recordings, often from tutorials, gameplay, or software demos." },
  legacy: { name: "Legacy / VHS", description: "Terms related to older media formats like VHS tapes (e.g., VTS_01)." },
  game_capture: { name: "Game Captures", description: 'Searches for gameplay videos from consoles or PCs with filenames like "DVR" or "Robloxapp".' },
  format: { name: "File Formats", description: 'Directly searching for video file extensions like ".MP4" or ".MOV", which can reveal accidental uploads.' },
  zoom: { name: "Zoom", description: "Looks for cloud recordings from Zoom meetings which sometimes get uploaded publicly." },
  vr: { name: "VR Headsets", description: "Finds raw video files uploaded from VR headsets like the Oculus/Meta Quest." },
  gopro: { name: "GoPro", description: "Common filename patterns from GoPro action cameras (e.g., GOPRXXXX)." },
  drone: { name: "Drones", description: "Searches for video files from drones, primarily using DJI naming conventions." },
  handheld: { name: "Handhelds", description: "Finds videos from handheld devices like the Nintendo DS." },
  audio: { name: "Audio", description: "Unusual searches that may be tied to audio recording devices or software." },
  bodycam: { name: "Bodycams", description: "Looks for footage uploaded from Axon body cameras or similar devices." },
  dashcam: { name: "Dashcams", description: "Common filenames from dashcam devices." }
};
